name: Current VM Information 1

on:
  push:

jobs:
  vm_info:
    runs-on: ubuntu-latest
    steps:
    - name: Display current VM information
      run: |
        echo "Operating System: ${{ runner.os }}"
        echo "Runner Type: ${{ runner.runnerType }}"
        echo "Hostname: ${{ runner.hostname }}"
        echo "Virtual Environment Image: ${{ runner.image }}"
        sleep 60
