name: Current VM Information 2

on:
  push:
    # workflow_dispatch:

jobs:
  vm_info:
    runs-on: flash-2cpu-2GB
    steps:
    - name: Display current VM information
      run: |
        echo "Operating System: ${{ runner.os }}"
        echo "Runner Type: ${{ runner.runnerType }}"
        echo "Hostname: ${{ runner.hostname }}"
        echo "Virtual Environment Image: ${{ runner.image }}"
        sleep 60
